CREATE TABLE IF NOT EXISTS schema_migrations (
  version INTEGER PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS research_tasks (
  id TEXT PRIMARY KEY,
  revision INTEGER NOT NULL DEFAULT 0,
  intake_state JSONB NOT NULL,
  intake_result JSONB,
  status TEXT NOT NULL DEFAULT 'clarifying',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS request_versions (
  task_id TEXT NOT NULL REFERENCES research_tasks(id),
  version INTEGER NOT NULL,
  payload JSONB NOT NULL,
  payload_sha256 CHAR(64) NOT NULL,
  confirmed_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (task_id, version),
  UNIQUE (task_id, payload_sha256)
);

CREATE TABLE IF NOT EXISTS design_versions (
  task_id TEXT NOT NULL,
  version INTEGER NOT NULL,
  request_version INTEGER NOT NULL,
  payload JSONB NOT NULL,
  payload_sha256 CHAR(64) NOT NULL,
  status TEXT NOT NULL DEFAULT 'proposed',
  reviewer TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (task_id, version),
  FOREIGN KEY (task_id, request_version) REFERENCES request_versions(task_id, version)
);

CREATE TABLE IF NOT EXISTS execution_requests (
  id TEXT PRIMARY KEY,
  task_id TEXT NOT NULL,
  design_version INTEGER NOT NULL,
  payload_sha256 CHAR(64) NOT NULL,
  status TEXT NOT NULL DEFAULT 'frozen',
  approved_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (task_id, design_version),
  FOREIGN KEY (task_id, design_version) REFERENCES design_versions(task_id, version)
);

CREATE TABLE IF NOT EXISTS job_attempts (
  id TEXT PRIMARY KEY,
  execution_id TEXT NOT NULL REFERENCES execution_requests(id),
  generation INTEGER NOT NULL DEFAULT 1,
  attempt INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'queued',
  origin TEXT NOT NULL DEFAULT 'simulation',
  external_job_id TEXT,
  error_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (execution_id, generation, attempt)
);

CREATE TABLE IF NOT EXISTS raw_artifacts (
  id TEXT PRIMARY KEY,
  attempt_id TEXT NOT NULL REFERENCES job_attempts(id),
  kind TEXT NOT NULL,
  relative_path TEXT NOT NULL UNIQUE,
  size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
  sha256 CHAR(64) NOT NULL,
  origin TEXT NOT NULL CHECK (origin IN ('simulation', 'real', 'demo')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id TEXT REFERENCES research_tasks(id),
  actor TEXT NOT NULL,
  action TEXT NOT NULL,
  details JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_audit_task ON audit_events(task_id, id);

CREATE TABLE IF NOT EXISTS intake_operations (
  operation_id TEXT PRIMARY KEY,
  task_id TEXT NOT NULL REFERENCES research_tasks(id),
  revision INTEGER NOT NULL,
  result JSONB NOT NULL,
  request_version INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO schema_migrations (version) VALUES (1) ON CONFLICT DO NOTHING;
